Require Import List.
Require Import String.
Require Import Omega.
Require Import Cubes.axioms
        Cubes.sprop_utils
        Cubes.arith_lemmas
        Cubes.hott_lemmas
        Cubes.cubes
        Cubes.cartesian.

Require Export Template.monad_utils
        Template.Ast
        Template.AstUtils
        Template.Template
        Template.LiftSubst
        Template.Checker
        Template.Typing
        Template.Induction.

Require Export Forcing.TemplateForcing
        Forcing.translation_utils
        Forcing.Inductives.


(** Check that category laws are definitional *)

Theorem compose_assoc {A B C D : nat}
           (f : A ~> B) (g : B ~> C) (h : C ~> D) :
  h ô (g ô f) = (h ô g) ô f.
Proof.
  reflexivity.
Qed.

Theorem compose_id_right {A B : nat} (f : A ~> B) :
  f ô id = f.
Proof.
  reflexivity.
Qed.

Theorem compose_id_left {A B : nat} (f : A ~> B) :
  id ô f = f.
Proof.
  reflexivity.
Qed.





(** Definition of the forcing machinery *)

Definition 𝐂_obj := nat.
Definition 𝐂_hom := arrow.
Definition 𝐂_id := @id.
Definition 𝐂_comp := @compose.

Quote Definition q_𝐂_obj := nat.
Quote Definition q_𝐂_hom := arrow.
Quote Definition q_𝐂_id := @id.
Quote Definition q_𝐂_comp := @compose.

Definition 𝐂 : category :=
  mkCat q_𝐂_obj q_𝐂_hom q_𝐂_id q_𝐂_comp.


Import MonadNotation.
Import ListNotations.

Definition ForcingTranslation (cat : category) : Translation :=
  {| tsl_id := tsl_ident;
     tsl_tm := f_translate cat;
     tsl_ty := f_translate_type cat;
     tsl_ind := f_translate_ind cat
     (* tsl_context -> kername -> kername -> mutual_inductive_body *)
     (*             -> tsl_result (tsl_table * list mutual_inductive_body) *)
  |}.

Definition add_translation (ctx : tsl_context) (e : global_reference * term): tsl_context :=
  let (Σ, E) := ctx in
  (Σ, e :: E).

Instance Cubical : Translation := ForcingTranslation 𝐂.

(* Define a type that, when recursively quoted, imports all we need *)
Definition pack := (arrow , @compose , @id).

Run TemplateProgram (prg <- tmQuoteRec pack ;;
                         tmDefinition "g_ctx" (fst prg)).
Definition ΣE : tsl_context := (reconstruct_global_context g_ctx,[]).



(** Imported inductives *)

(* We copy translated definitions of [eq] generated by the OCaml
   forcing plugin, because inducives are not supported yet by the
   template-coq forcing translation *)
Inductive eqᵗ (p : 𝐂_obj) (A : forall p0 : 𝐂_obj, p ~> p0 -> forall p : 𝐂_obj, p0 ~> p -> Type)
(x : forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 (α ô id) p0 id) :
  (forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 (id ô (α ô id)) p0 id) -> Type :=
  eq_reflᵗ : eqᵗ p A x x.

(* This definition will fail if we leave the type of [A] implicit. *)
Definition eq_is_eq :
  forall p (A : forall x : 𝐂_obj, (p ~> x) -> forall x1 : 𝐂_obj, (x ~> x1) -> Type)
         (x y: forall p0 (f:p ~> p0), A p0 f p0 id),
    eq x y -> eqᵗ p A x y. (* it even fails if i don't mention A as an explicit argument
                             here b/c of some mysterious reason *)
Proof.
  intros. rewrite H. apply eq_reflᵗ.
Qed.

Run TemplateProgram (TC <- tAddExistingInd ΣE "Coq.Init.Logic.eq" "eqᵗ" ;;
                          tmDefinition "eq_TC" TC).

Inductive Falseᵗ (p : 𝐂_obj) := .

Run TemplateProgram (TC <- tAddExistingInd eq_TC "Coq.Init.Logic.False" "Falseᵗ" ;;
                        tmDefinition "False_TC" TC).

Inductive orᵗ (p : 𝐂_obj) (A B : forall p0 : 𝐂_obj, p ~> p0 -> forall p1 : 𝐂_obj, p0 ~> p1 -> Prop) : Prop :=
    or_introlᵗ : (forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 α p0 id) -> orᵗ p A B
  | or_introrᵗ : (forall (p0 : 𝐂_obj) (α : p ~> p0), B p0 α p0 id) -> orᵗ p A B.

Run TemplateProgram (TC <- tAddExistingInd False_TC "Coq.Init.Logic.or" "orᵗ" ;;
                        tmDefinition "or_TC" TC).

Inductive andᵗ (p : 𝐂_obj) (A B : forall p0 : 𝐂_obj, p ~> p0 -> forall p1 : 𝐂_obj, p0 ~> p1 -> Prop) : Prop :=
    conjᵗ : (forall (p0 : 𝐂_obj) (α : p ~> p0), A p0 α p0 id) ->
            (forall (p0 : 𝐂_obj) (α : p ~> p0), B p0 α p0 id) -> andᵗ p A B.

Run TemplateProgram (TC <- tAddExistingInd or_TC "Coq.Init.Logic.and" "andᵗ" ;;
                        tmDefinition "and_TC" TC).

Inductive sigTᵗ (p : 𝐂_obj)
          (A : forall p0, p ~> p0 -> forall p, p0 ~> p -> Type)
          (P : forall p0 (α : p ~> p0),
              (forall p (α0 : p0 ~> p), A p (α0 ô α) p id) ->
              forall p, p0 ~> p -> Type) : Type :=
  existTᵗ : forall x : forall p0 (α : p ~> p0), A p0 α p0 id,
    (forall p0 (α : p ~> p0), P p0 α (fun (q : 𝐂_obj) (α0 : p0 ~> q) => x q (α0 ô α)) p0 id) ->
    sigTᵗ p A P.

Run TemplateProgram (TC <- tAddExistingInd and_TC "Coq.Init.Specif.sigT" "sigTᵗ" ;;
                        tmDefinition "sigT_TC" TC).

Inductive unitᵗ (p : 𝐂_obj) :=
  ttᵗ : unitᵗ p.

Run TemplateProgram (TC <- tAddExistingInd sigT_TC "Coq.Init.Datatypes.unit" "unitᵗ" ;;
                        tmDefinition "unit_TC" TC).

Definition complete_TC := unit_TC.
